[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"

# Define edge function handler
[[edge_functions]]
  path = "/api/generate-code"
  function = "generate-code"

# Global edge functions configuration
[edge_handlers_config]
  included_files = ["netlify/edge-functions/**"]
  external_node_modules = ["@anthropic-ai/sdk", "@google/generative-ai"] 