[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@anthropic-ai/sdk", "@google/generative-ai"]

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"

# Define edge function handler with increased timeout
[[edge_functions]]
  path = "/api/generate-code"
  function = "generate-code"
  cache = "manual"

[[edge_functions]]
  path = "/api/generate-code/*"
  function = "generate-code"
  cache = "manual"

# Global edge functions configuration
[edge_handlers_config]
  included_files = ["netlify/edge-functions/**"]
  external_node_modules = ["@anthropic-ai/sdk", "@google/generative-ai"]

# Increase timeouts for functions
[functions.generate-code]
  included_files = ["netlify/edge-functions/**"]
  external_node_modules = ["@anthropic-ai/sdk", "@google/generative-ai"]
  timeout = 120 # 120 seconds for code generation

# Add headers for CSS files
[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css" 