[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@anthropic-ai/sdk", "@google/generative-ai"]

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"

# Define edge function handler
[[edge_functions]]
  path = "/api/generate-code"
  function = "generate-code"

[[edge_functions]]
  path = "/api/generate-code/*"
  function = "generate-code"

[[edge_functions]]
  path = "/api/chat-with-images"
  function = "chat-with-images"

[[edge_functions]]
  path = "/api/chat-with-images/*"
  function = "chat-with-images"

# Global edge functions configuration
[edge_handlers_config]
  included_files = ["netlify/edge-functions/**"]
  external_node_modules = ["@anthropic-ai/sdk", "@google/generative-ai"]

# Increase timeouts for edge functions
[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = true
[functions.generate-code]
  included_files = ["netlify/edge-functions/**"]
  external_node_modules = ["@anthropic-ai/sdk", "@google/generative-ai"]
  timeout = 30
[functions.chat-with-images]
  included_files = ["netlify/edge-functions/**"]
  external_node_modules = ["@anthropic-ai/sdk", "@google/generative-ai"]
  timeout = 60

# Add headers for CSS files
[[headers]]
  for = "/_next/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css" 