[build]
  command = "npm run build"
  publish = ".next"

[[edge_functions]]
  function = "generate-code"
  path = "/api/generate-code"

# Regular serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle Next.js routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 